### ISSUE TITLE
General discussion on the look and feel of the game

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#3]
- 2D: I think the game should be 2D because the scope of a 2D game is much smaller and easier to manage
  - Top down: It could be top down, like [the original Hunt the Wumpus](http://www.oldschoolapps.com/files/img/huntthewumpus.png), but with more flushed out graphics presumably
  - Side scroller: I think this could be made to work if we really like the idea?
  - [A "2.5D" RPG sort of look](https://www.ehow.com/default/ehow/images/a04/9a/l1/make-own-2d-game-800x800.jpg)
 - 3D: 3D might have more options for gameplay but would be harder and might look worse if not done right
  - First person dungeon crawler ([Prelude of the Chambered](https://i.ytimg.com/vi/RE3dRh4wMc8/hqdefault.jpg))

**Comment by WasabiFan** [comment]
@kyranstar I generally agree with your analysis; 2D would definitely be easier. One of the things that I have seen from most of the demos of previous games is that the player never actually *sees* more than one room at a time. I was thinking it might be interesting to look into a fog-like effect, so that everything outside of the user's current room was obscured.

Aside from the complexities of 3D, one of the other main challenges is the actual gameplay. Running around in 1st-person answering trivia isn't something that I would consider thrilling. If we kept it top-down and just rendered it as 3D, I think that might be a great balance of graphic fidelity, gameplay, and simplicity. I think this is what you meant by "2.5D RPG".

I don't particularly like the idea of a side-scroller; the spec requires us to have multiple doors (situated in a hexagonal fashion), which would be hard to illustrate in a that style of game. It could easily get confusing for the player.

**Comment by nikbyk** [comment]
What kind of theme are we looking at for the game?

**Comment by BlueRosesSonyPony** [comment]
If we're not doing the environmental competition, maybe an ocean theme? The
player could swim through underground caves, and the wumpus could be a
kraken or octopus or something.

Or if we're going with the environmental theme, we could have a
post-apocalyptic landscape and the trivia could be about things that people
could have done in the past to prevent this global catastrophe.

**Comment by kyranstar** [comment]
We need more information about that environmental competition. Is there a link?

**Comment by kyranstar** [comment]
I found a game that has a pretty unique look. It's a puzzle game, but it has an electricity theme, which could go along with the environmental thing. One of the quotes from the person playing the game is something I really agree with, "It's nice to see something stylized without it being pixel graphics." I feel like pixel graphics are a bit overdone so I don't know if we should do them.

[![1000 Amps](http://img.youtube.com/vi/0v6MVselwbY/0.jpg)](http://www.youtube.com/watch?v=0v6MVselwbY)

**Comment by nikbyk** [comment]
I don't really like the whole environmental theme. I agree with the last comment. Something stylish might be nice, like Limbo.

**Comment by WasabiFan** [comment]
Yeah, I'd say we should go for whatever looks best.

**Comment by WasabiFan** [comment]
Just an idea: since we are going monochrome, I think a "ghost" theme might be an option -- the Wumpus is a shadowy ghost. What do you think?

**Comment by nikbyk** [comment]
that would be nice

**Comment by WasabiFan** [comment]
How do we want to handle the fog? The goal is to obscure the adjacent rooms so that you can't see them, but currently it just looks pathetic.

So, what do we want to do about it? The easiest thing to do would be to draw the current room on top of the fog, while all the other rooms are below. That would work, but then we're have to figure out how we want to render the effect when you travel from one room to another.

Another option is to use much smaller particles and fade them based on their distance from the player (or the center of the room). I think this would be the coolest-looking option, but that means drawing many more particles -- and our code is so inefficient that 600 is a stretch on some machines.

Our last option is to kill the fog (sadface) and make it a black or dray background with a hole cut out so that you can see the player and the current room.

Are there any more options that you can think of? Which do you think is the best?

**Comment by kyranstar** [comment]
I think we should only draw the rooms we've visited, and just not render the rest, and make the fog thick enough to look like it's obscuring them. We can try to make the fog stay out of the currently visible rooms. And then when we move into a new room, just fade out the fog currently in that room.

We should have a better system for positioning fog in order to have some sort of uniform density throughout the places that are supposed to be covered.

**Comment by nikbyk** [comment]
I set the fog opacity low for now, because it doesn't stay out of the current room yet





        Sent by Outlook for Android




On Sun, Apr 26, 2015 at 3:49 PM -0700, "Kyran Adams" <notifications@github.com> wrote:
I think we should only draw the rooms we've visited, and just not render the rest, and make the fog thick enough to look like it's obscuring them. We can try to make the fog stay out of the currently visible rooms. And then when we move into a new room, just fade out the fog currently in that room.

We should have a better system for positioning fog in order to have some sort of uniform density throughout the places that are supposed to be covered.

---

**Comment by WasabiFan** [comment]
> We can try to make the fog stay out of the currently visible rooms...

I think you're being overly optimistic :wink:. I've spent longer that I would like to admit attempting to make the fog *stay away* but it always ends up being complicated, buggy, or just plain broken. Do you have an idea for how we can do this?

I think the first step is to replace the selective generation with a randomized point within the current view. Currently, after we create a particle, *it moves* -- which voids the calculations that it made to position it outside the room.

**Comment by nikbyk** [comment]
We could start with stationary particles then.





        Sent by Outlook for Android




On Sun, Apr 26, 2015 at 3:56 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
> We can try to make the fog stay out of the currently visible rooms...

I think you're being overly optimistic :wink:. I've spent longer that I would like to admit attempting to make the fog *stay away* but it always ends up being complicated, buggy, or just plain broken. Do you have an idea for how we can do this?

I think the first step is to replace the selective generation with a randomized point within the current view. Currently, after we create a particle, *it moves* -- which voids the calculations that it made to position it outside the room.

---

**Comment by WasabiFan** [comment]
@nikbyk Can you trim the transparent pixels off of the side of the single coin image? I'd like to handle margins programmatically instead of having any built into the image itself.

**Comment by nikbyk** [comment]
Will do, will push tonight or tomorrow.





        Sent by Outlook for Android




On Sun, May 3, 2015 at 7:35 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk Can you trim the transparent pixels off of the side of the single coin image? I'd like to handle margins programmatically instead of having any built into the image itself.

---

**Comment by WasabiFan** [comment]
Sounds good. I'm using the coin image in the HUD as an icon next to the user's remaining gold and it's pretty small when we include two separate margins. But the image itself looks good!

**Comment by nikbyk** [comment]
Great





        Sent by Outlook for Android




On Sun, May 3, 2015 at 7:42 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
Sounds good. I'm using the coin image in the HUD as an icon next to the user's remaining gold and it's pretty small when we include two separate margins. But the image itself looks good!

---

**Comment by WasabiFan** [comment]
@nikbyk Oh, and if you get a chance, can you make an arrow thumbnail as well?

**Comment by nikbyk** [comment]
Absolutely





        Sent by Outlook for Android




On Sun, May 3, 2015 at 8:51 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
@nikbyk Oh, and if you get a chance, can you make an arrow thumbnail as well?

---

**Comment by WasabiFan** [comment]
How do we want to handle rendering the wumpus? Currently, we draw all of the rooms that the user has traveled through (and their adjacent ones). If the wumpus moves into one of those rooms, do we want to let the user see it? If not, we need to dim the rooms that the user has passed through but is not currently in so that they know that things are being hidden. But at that point, is there a reason that we don't just dim the rooms again after the user leaves them?
