### ISSUE TITLE
Cave generation throwing assertion errors

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#39]
As I am debugging our game, I am repeatedly hitting debug error dialogs because assertions are failing in the cave generator. I think that we should replace these debug assertions with error/warning logging so that we don't show the judges a big error dialog when we start the game. I think it would be easiest to define an `Assert` method in our `Log` class that perforns the same core function as `Debug.Assert` but just logs instead of `MessageBox`es.

**Comment by nikbyk** [comment]
That's a good idea, thought it was just me


Sent by Outlook for Android





On Fri, May 22, 2015 at 11:42 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
As I am debugging our game, I am repeatedly hitting debug error dialogs because assertions are failing in the cave generator. I think that we should replace these debug assertions with error/warning logging so that we don't show the judges a big error dialog when we start the game. I think it would be easiest to define an `Assert` method in our `Log` class that perforns the same core function as `Debug.Assert` but just logs instead of `MessageBox`es.

---
Reply to this email directly or view it on GitHub:
https://github.com/kyranstar/Hunt-The-Wumpus/issues/39

**Comment by kyranstar** [comment]
Is it just the cave wrapping that's throwing errors?

**Comment by WasabiFan** [comment]
It was in `MapGenerator` line 184, I think.

**Comment by kyranstar** [comment]
Okay. Well since I commented out the `AddSideConnections` method we can probaly close this issue
