### ISSUE TITLE
Cave wrapping getting confusing

### ISSUE THREAD

**Issue by WasabiFan** [kyranstar/Hunt-The-Wumpus#40]
Since we determined that we don't want to follow a strict grid pattern, I think that we should disable the cave wrapping in the generator. Currently, I find myself in confusing situations where the wrapping just makes navigating more of a pain than an interesting element. What do you guys think?

**Comment by anak4569** [comment]
Guys, I would like to help on certain issues that we need to get done, but I'm not sure which ones are our priority. Could someone tell me which issues are 1st priority, 2nd priority, etc. so I can start working?

**Comment by nikbyk** [comment]
I'm pretty sure wrapping is in the spec


Sent by Outlook for Android





On Fri, May 22, 2015 at 11:45 PM -0700, "Wasabi Fan" <notifications@github.com> wrote:
Since we determined that we don't want to follow a strict grid pattern, I think that we should disable the cave wrapping in the generator. Currently, I find myself in confusing situations where the wrapping just makes navigating more of a pain than an interesting element. What do you guys think?

---
Reply to this email directly or view it on GitHub:
https://github.com/kyranstar/Hunt-The-Wumpus/issues/40

**Comment by WasabiFan** [comment]
> I'm pretty sure wrapping is in the spec

You're right -- it is. But personally, I'd rather have a more interesting & less confusing game than follow the spec 100%. It's not a big issue, so if we want to keep it as-is that's fine.

> Could someone tell me which issues are 1st priority, 2nd priority, etc. so I can start working?

The issues labeled `required for spec` are 1st priority, the ones labeled `important (not required)` are 2nd. Feel free to pick any issue, assign it to yourself, and start working on it!
