### ISSUE TITLE
Where to put test code

### ISSUE THREAD

**Issue by kyranstar** [kyranstar/Hunt-The-Wumpus#7]
Where should I put test methods? And how can I run them?

**Comment by WasabiFan** [comment]
Honestly, I don't know... I have never used it in VS before. I know that testing is built in to VS though.

If you don't want to pioneer the way yourself, I'd recommend that you write the code somewhere in our existing code base with an error log if it fails and do it that way until I can do some research. I know that's a pretty bad way to write tests, but it's our best option for now 😡

**Comment by kyranstar** [comment]
Okay. It says [here](https://www.visualstudio.com/en-us/get-started/create-and-run-unit-tests-vs.aspx) how to set up a testing project so I'll try that when I get home?

**Comment by WasabiFan** [comment]
Sounds good. If/when you create it in the repo solution, tell it to put the project in either a "Test" folder under "platform" or in a "Test" folder one level above that.

To add our files so that they are auto-discovered, you will have to edit the generated project file manually -- you can use the desktop one as an example.
